name: weather_app_flutter
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  get: ^4.6.5
  get_storage: ^2.1.1
  sizer: ^2.0.15
  pull_to_refresh: ^2.0.0
  dio: ^4.0.6
  freezed: ^2.1.0+1
  retrofit: any
  retrofit_generator: any
  flutter_secure_storage: ^6.0.0
  logger: ^2.0.2
  equatable: ^2.0.5
  flutter_form_builder: ^7.7.0
  form_builder_validators: ^8.4.0
  flutter_staggered_grid_view: ^0.6.2
  intl: ^0.17.0
  flutter_custom_dialog: ^1.3.0
  geolocator: ^10.0.0
  device_preview: ^1.1.0
  firebase_core: ^2.20.0
  google_sign_in: ^5.4.2
  firebase_auth: ^4.12.0
  http: ^0.13.5

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: any
  flutter_gen_runner: null
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/resources/

flutter:
  uses-material-design: true
  assets:
    - lib/resources/images/
  fonts:
    - family: avenir
      fonts:
        - asset: lib/resources/fonts/avenir_book.otf
          weight: 400
        - asset: lib/resources/fonts/avenir_medium.otf
          weight: 500
        - asset: lib/resources/fonts/avenir_heavy.ttf
          weight: 700
        - asset: lib/resources/fonts/avenir_roman.otf
          weight: 900
