// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgUvMKroblTgIP77MxidKNPuX8TsU2c9g',
    appId: '1:316820023865:web:a3f7ae33af1ebaddee3be8',
    messagingSenderId: '316820023865',
    projectId: 'weather-app-d8036',
    authDomain: 'weather-app-d8036.firebaseapp.com',
    storageBucket: 'weather-app-d8036.appspot.com',
    measurementId: 'G-84N4N2DSEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH6etBP_5S5EmjLKWAj36newnNyW8qvWE',
    appId: '1:316820023865:android:3492b9ba9a77a9f8ee3be8',
    messagingSenderId: '316820023865',
    projectId: 'weather-app-d8036',
    storageBucket: 'weather-app-d8036.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO_JX3F4wLcw_P0KwYmxJqcBNpWN-MZko',
    appId: '1:316820023865:ios:e5f5d3736b8e4eacee3be8',
    messagingSenderId: '316820023865',
    projectId: 'weather-app-d8036',
    storageBucket: 'weather-app-d8036.appspot.com',
    iosBundleId: 'com.example.weatherAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO_JX3F4wLcw_P0KwYmxJqcBNpWN-MZko',
    appId: '1:316820023865:ios:e5f5d3736b8e4eacee3be8',
    messagingSenderId: '316820023865',
    projectId: 'weather-app-d8036',
    storageBucket: 'weather-app-d8036.appspot.com',
    iosBundleId: 'com.example.weatherAppFlutter',
  );
}
